syntax enable
set number
set relativenumber
set showmatch
set mouse=a
set backspace=2
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
set cindent
set colorcolumn=80

autocmd BufEnter * colorscheme darkblue
autocmd BufEnter *.sh colorscheme delek
